apiVersion: v1
kind: Pod
metadata:
  name: tgis-grpc-load-flan-t5-small
spec:
  restartPolicy: Always
  containers:
  - name: tgis-grpc-load-flan
    image: docker.io/anubhavjana18/gpu_load:grpc_inference-v5
    imagePullPolicy: IfNotPresent
    env:
    - name: REQUEST_URL
      value: "10.128.5.51:8033"
    - name: ITERATIONS
      value: "1800"
    - name: TOKEN_SIZE
      value: "500"
    - name: REQUEST_RATE
      value: "5"
    - name: BATCH_SIZE
      value: "1"
    - name: TLS_AUTH
      value: "disabled"
    - name: USER
      value: "Alan"

    