apiVersion: v1
kind: Pod
metadata:
  name: tgis-grpc-load-llama3-router
spec:
  restartPolicy: Always
  containers:
  - name: tgis-grpc-load-llama3-router
    image: docker.io/felixgeorge/loadgen:user
    imagePullPolicy: Always
    env:
    - name: REQUEST_URL
      value: "10.131.0.16:8032"
    - name: ITERATIONS
      value: "1800"
    - name: TOKEN_SIZE
      value: "500"
    - name: REQUEST_RATE
      value: "5"
    - name: BATCH_SIZE
      value: "1"
    - name: TLS_AUTH
      value: "disabled"
    - name: USERS
      value: "[{\"user_id\":\"Alan\",\"model_id\":\"llama3\",\"latency\":20,\"request_rate\":30,\"out_token_size\":200,\"batch_size\":1,\"variable_token_size\":false,\"iterations\":1800},{\"user_id\":\"Noel\",\"model_id\":\"llama3\",\"latency\":50,\"request_rate\":30,\"out_token_size\":200,\"batch_size\":1,\"variable_token_size\":false,\"iterations\":1800},{\"user_id\":\"Hari\",\"model_id\":\"bloom\",\"latency\":10,\"request_rate\":30,\"out_token_size\":200,\"batch_size\":1,\"variable_token_size\":false,\"iterations\":1800}]"
    - name: DUMP_RESPONSE
      value: "disabled"
