apiVersion: v1
kind: Pod
metadata:
  name: tgis-grpc-load-llama7b
spec:
  restartPolicy: Always
  containers:
  - name: tgis-grpc-load-llama7b
    image: docker.io/felixgeorge/gpu_load:grpc_inference
    imagePullPolicy: IfNotPresent
    env:
    - name: REQUEST_URL
      value: "10.128.2.89:8033"
    - name: ITERATIONS
      value: "2"
    - name: TOKEN_SIZE
      value: "500"
    - name: THREADS
      value: "1"
    - name: BATCH_SIZE
      value: "1"
    - name: TLS_AUTH
      value: "disabled"