# apiVersion: v1
# kind: Pod
# metadata:
#   name: tgis-grpc-load-llama
# spec:
#   restartPolicy: Always
#   containers:
#   - name: tgis-grpc-load-llama
#     image: docker.io/felixgeorge/loadgen:load-gen-v1
#     imagePullPolicy: IfNotPresent
#     env:
#     - name: REQUEST_URL
#       value: "10.131.0.47:8032"
#     - name: ITERATIONS
#       value: "1800"
#     - name: TOKEN_SIZE
#       value: "500"
#     - name: REQUEST_RATE
#       value: "5"
#     - name: BATCH_SIZE
#       value: "1"
#     - name: TLS_AUTH
#       value: "disabled"
#     - name: USERS
#       value: "[{\"user_id\":\"Alan\",\"model_id\":\"llama3\",\"latency\":20,\"request_rate\":100,\"out_token_size\":500,\"batch_size\":1,\"variable_token_size\":true,\"iterations\":1},{\"user_id\":\"Noel\",\"model_id\":\"llama3\",\"latency\":50,\"request_rate\":200,\"out_token_size\":100,\"batch_size\":1,\"variable_token_size\":false,\"iterations\":3},{\"user_id\":\"Hari\",\"model_id\":\"bloom\",\"latency\":10,\"request_rate\":300,\"out_token_size\":100,\"batch_size\":1,\"variable_token_size\":true,\"iterations\":2}]"
#     - name: DUMP_RESPONSE
#       value: "disabled"

apiVersion: v1
kind: Pod
metadata:
  name: tgis-grpc-load-vllm-llama
spec:
  restartPolicy: Always
  containers:
  - name: tgis-grpc-load-vllm-llama
    image: docker.io/anubhavjana18/gpu_load:grpc_inference-v5
    imagePullPolicy: IfNotPresent
    env:
    - name: REQUEST_URL
      value: "10.130.5.69:8033"
    - name: ITERATIONS
      value: "1800"
    - name: TOKEN_SIZE
      value: "500"
    - name: THREADS
      value: "1"
    - name: BATCH_SIZE
      value: "1"
    - name: TLS_AUTH
      value: "disabled"
    - name: REQUEST_RATE
      value: "5"