apiVersion: v1
kind: Pod
metadata:
  name: load-generator-tgis
  namespace: fmaas-monitoring
spec:
  containers:
  - name: load-generator-tgis
    image: docker.io/felixgeorge/loadgen:user
    imagePullPolicy: Always
    env:
    - name: REQUEST_URL
      value: "10.128.4.8:8033"
    - name: TLS_AUTH
      value: "disabled"
    - name: USERS
      value: "[{\"user_id\":\"Alan\",\"model_id\":\"llama3\",\"latency\":20,\"request_rate\":5,\"out_token_size\":60,\"batch_size\":1,\"variable_token_size\":false,\"iterations\":1800},{\"user_id\":\"Noel\",\"model_id\":\"llama3\",\"latency\":50,\"request_rate\":5,\"out_token_size\":180,\"batch_size\":1,\"variable_token_size\":false,\"iterations\":1800}]"
    - name: DUMP_RESPONSE
      value: "disabled"